# Generated by Django 5.0.1 on 2024-01-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatarName",
            field=models.CharField(blank=True, default="a", max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="goal",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
