# Generated by Django 5.0.1 on 2024-01-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_is_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatarName",
            field=models.CharField(blank=True, default="Mensch-1", max_length=255),
        ),
    ]
