# Generated by Django 5.0.1 on 2024-01-12 12:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_user_goal_goal"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goal",
            old_name="goal_text",
            new_name="goal",
        ),
    ]
