# Generated by Django 5.0.1 on 2024-01-12 13:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_rename_goal_text_goal_goal"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goal",
            old_name="end_date",
            new_name="endDate",
        ),
        migrations.RenameField(
            model_name="goal",
            old_name="start_date",
            new_name="startDate",
        ),
    ]
