# Generated by Django 5.0.1 on 2024-01-12 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0001_initial"),
        ("users", "0007_rename_end_date_goal_enddate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="agent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="agents.agent",
            ),
        ),
    ]
