# Generated by Django 5.0.1 on 2024-01-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_remove_user_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="endDate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="goal",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="startDate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
