# Generated by Django 5.0.1 on 2024-01-17 15:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0002_state"),
    ]

    operations = [
        migrations.RenameField(
            model_name="state",
            old_name="Agent",
            new_name="agent",
        ),
    ]
