# Generated by Django 5.0.1 on 2024-01-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0003_rename_agent_state_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="state",
            name="current_state",
            field=models.IntegerField(),
        ),
    ]
